'use strict';

module.exports = Object.freeze({
    RANK_1: 0,
    RANK_2: 1,
    RANK_3: 2,
    RANK_4: 3,
    RANK_5: 4,
    RANK_6: 5,
    RANK_7: 6,
    RANK_8: 7,
    FILE_A: 0,
    FILE_B: 1,
    FILE_C: 2,
    FILE_D: 3,
    FILE_E: 4,
    FILE_F: 5,
    FILE_G: 6,
    FILE_H: 7,
    LICHESS_FILE_A: 'a',
    LICHESS_FILE_B: 'b',
    LICHESS_FILE_C: 'c',
    LICHESS_FILE_D: 'd',
    LICHESS_FILE_E: 'e',
    LICHESS_FILE_F: 'f',
    LICHESS_FILE_G: 'g',
    LICHESS_FILE_H: 'h',
    FRONTEND_FILES: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],

    EMPTY: '*',
    W_PAWN: 'P',
    W_KNIGHT: 'N',
    W_BISHOP: 'B',
    W_ROOK: 'R',
    W_QUEEN: 'Q',
    W_KING: 'K',
    B_PAWN: 'p',
    B_KNIGHT: 'n',
    B_BISHOP: 'b',
    B_ROOK: 'r',
    B_QUEEN: 'q',
    B_KING: 'k',

    EVENT_PROCESSOR_UPDATE_BOARD: 'epub',
    EVENT_PROCESSOR_GAME_START: 'epgs',
    EVENT_PROCESSOR_GAME_END: 'epge',
    EVENT_SOCKET_UPDATE_BOARD: 'esub',
    EVENT_SOCKET_GAME_START: 'esgs',
    EVENT_SOCKET_GAME_END: 'esge',
    EVENT_STREAM_GAME_STATE_DATA: 'esgsd',
    EVENT_STREAM_GAME_STATE_END: 'esgse',
    EVENT_STREAM_INCOMING_EVENTS_DATA: 'esied',

    GAME_STATUS_OOT: 'outoftime',
    GAME_STATUS_STALEMATE: 'stalemate',
    GAME_STATUS_DRAW: 'draw',
    GAME_STATUS_CHECKMATE: 'mate',
    GAME_STATUS_RESIGN: 'resign',
    GAME_STATUS_ABORTED: 'aborted',

    IMG_W_PAWN: 'white_pawn.svg',
    IMG_W_KNIGHT: 'white_knight.svg',
    IMG_W_BISHOP: 'white_bishop.svg',
    IMG_W_ROOK: 'white_rook.svg',
    IMG_W_QUEEN: 'white_queen.svg',
    IMG_W_KING: 'white_king.svg',
    IMG_B_PAWN: 'black_pawn.svg',
    IMG_B_KNIGHT: 'black_knight.svg',
    IMG_B_BISHOP: 'black_bishop.svg',
    IMG_B_ROOK: 'black_rook.svg',
    IMG_B_QUEEN: 'black_queen.svg',
    IMG_B_KING: 'black_king.svg'
});
